In [35]:
import numpy as np
import time

In [4]:
np.random.seed(7)
cities = np.array(["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Birgunj"])
days = np.array([f"D{i:02d}" for i in range(1, 15)])

In [5]:
temps = np.random.randint(14, 36, size=(5, 14)).astype(float)
humidity = np.random.randint(40, 95, size=(5, 14)).astype(float)

In [7]:
temps[2, 5] = np.nan
temps[4, 11] = np.nan

In [10]:
#B1 — Array anatomy and reshaping
print("B1a — temps.shape:", temps.shape)
print("B1a — temps.ndim:", temps.ndim)
print("B1a — temps.dtype:", temps.dtype)
print("B1a — temps.size:", temps.size)


B1a — temps.shape: (5, 14)
B1a — temps.ndim: 2
B1a — temps.dtype: float64
B1a — temps.size: 70


In [11]:
flat70 = np.arange(70)
reshaped_explicit = flat70.reshape(5, 14)
reshaped_neg1 = flat70.reshape(5, -1)
print("B1b — reshape(5,14) == reshape(5,-1):", np.array_equal(reshaped_explicit, reshaped_neg1))
back_to_flat = reshaped_explicit.flatten()
print("B1b — flattened back matches original:", np.array_equal(back_to_flat, flat70))

B1b — reshape(5,14) == reshape(5,-1): True
B1b — flattened back matches original: True


In [20]:
#B2 — Indexing and slicing
a = temps[1, 2]
print("B2a — Pokhara's day-3 temperature:", a, "and shape:", np.shape(a))

B2a — Pokhara's day-3 temperature: 14.0 and shape: ()


In [21]:
b = temps[:, -1]
print("B2b — every city's reading on the last day:", b, "and shape:", b.shape)

B2b — every city's reading on the last day: [30. 28. 21. 18. 30.] and shape: (5,)


In [22]:
c = temps[2, :]
print("B2c — Biratnagar's full fortnight:", c, "and shape:", c.shape)

B2c — Biratnagar's full fortnight: [20. 18. 28. 23. 17. nan 22. 33. 30. 15. 14. 30. 26. 21.] and shape: (14,)


In [23]:
d = temps[0:3, 3:8]
print("B2d — first three cities, days 4-8:\n", d, "and shape:", d.shape)

B2d — first three cities, days 4-8:
 [[33. 21. 28. 22. 28.]
 [25. 20. 33. 26. 19.]
 [23. 17. nan 22. 33.]] and shape: (3, 5)


In [24]:
e = temps[3, ::2]
print("B2e — every other day for Lalitpur:", e, "and shape:", e.shape)

B2e — every other day for Lalitpur: [24. 17. 21. 35. 17. 17. 33.] and shape: (7,)


In [25]:
f = temps[0, ::-1]
print("B2f — Kathmandu's fortnight reversed:", f, "and shape:", f.shape)

B2f — Kathmandu's fortnight reversed: [30. 18. 20. 21. 22. 24. 28. 22. 28. 21. 33. 17. 18. 29.] and shape: (14,)


In [26]:
#B3 — Boolean masks
mask_hot = temps > 30
print("B3a — readings above 30 per city:", mask_hot.sum(axis=1))

B3a — readings above 30 per city: [1 2 1 2 6]


In [27]:
kathmandu_hot_days = days[temps[0] > 30]
print("B3b — days Kathmandu exceeded 30:", kathmandu_hot_days)

B3b — days Kathmandu exceeded 30: ['D04']


In [28]:
#B4 — Views vs. copies
demo = temps.copy()

In [29]:
view_slice = demo[0, 0:3]
view_slice[0] = 999
print("B4 — demo array after modifying a VIEW (changed):\n", demo)

B4 — demo array after modifying a VIEW (changed):
 [[999.  18.  17.  33.  21.  28.  22.  28.  24.  22.  21.  20.  18.  30.]
 [ 21.  26.  14.  25.  20.  33.  26.  19.  35.  30.  14.  16.  23.  28.]
 [ 20.  18.  28.  23.  17.  nan  22.  33.  30.  15.  14.  30.  26.  21.]
 [ 24.  23.  17.  14.  21.  14.  35.  18.  17.  15.  17.  15.  33.  18.]
 [ 33.  15.  19.  23.  31.  16.  33.  32.  32.  35.  17.  nan  29.  30.]]


In [30]:
copy_slice = demo[1, 0:3].copy()
copy_slice[0] = 999
print("B4 — demo array after modifying a COPY (unchanged at [1,0]):", demo[1, 0])

B4 — demo array after modifying a COPY (unchanged at [1,0]): 21.0


In [33]:
#B5 — Vectorization vs. a Python loop
def to_fahrenheit_loop(arr):
    result = np.empty_like(arr)
    flat_in = arr.flatten()
    flat_out = result.flatten()
    for i in range(flat_in.size):
        flat_out[i] = flat_in[i] * 9 / 5 + 32
    return flat_out.reshape(arr.shape)
 
fahrenheit_loop = to_fahrenheit_loop(temps)
fahrenheit_vec = temps * 9 / 5 + 32
print("B5 — loop and vectorized agree:", np.allclose(fahrenheit_loop, fahrenheit_vec, equal_nan=True))

B5 — loop and vectorized agree: True


In [36]:
big = np.random.uniform(14, 36, size=1_000_000)
 
start = time.perf_counter()
big_loop_result = np.empty_like(big)
for i in range(big.size):
    big_loop_result[i] = big[i] * 9 / 5 + 32
loop_time = time.perf_counter() - start
 
start = time.perf_counter()
big_vec_result = big * 9 / 5 + 32
vec_time = time.perf_counter() - start
 
speedup = loop_time / vec_time
print(f"B5 — loop time: {loop_time:.4f}s")
print(f"B5 — vectorized time: {vec_time:.4f}s")
print(f"B5 — speedup: ~{speedup:.1f}x faster")

B5 — loop time: 1.4974s
B5 — vectorized time: 0.0381s
B5 — speedup: ~39.3x faster


In [37]:
#B6 — Broadcasting
city_avg = np.nanmean(temps, axis=1, keepdims=True)
anomaly = temps - city_avg
print("B6a — anomaly grid shape:", anomaly.shape, "| still (5,14):", anomaly.shape == (5, 14))

B6a — anomaly grid shape: (5, 14) | still (5,14): True


In [38]:
day_correction = np.random.uniform(-1, 1, size=14)
corrected = temps + day_correction
print("B6b — corrected shape:", corrected.shape)
 
try:
    bad = temps + np.array([1, 2, 3, 4, 5])
except ValueError as err:
    print("B6c — ValueError message:", err)

B6b — corrected shape: (5, 14)
B6c — ValueError message: operands could not be broadcast together with shapes (5,14) (5,) 


In [39]:
#B7 — Matrix multiplication
quantities = np.array([2, 3, 1])
prices = np.array([120, 90, 250])
print("B7a — element-wise (*):", quantities * prices)
print("B7a — dot product (@):", quantities @ prices)

B7a — element-wise (*): [240 270 250]
B7a — dot product (@): 760


In [40]:
#B8 — Aggregating along an axis
features = np.stack([
    np.nanmean(temps, axis=0),
    np.nanmean(humidity, axis=0)
], axis=1)
weights = np.array([0.6, -0.1])
comfort_score = features @ weights
print("B7b — features shape:", features.shape)
print("B7b — weights shape:", weights.shape)
print("B7b — comfort_score shape:", comfort_score.shape)

B7b — features shape: (14, 2)
B7b — weights shape: (2,)
B7b — comfort_score shape: (14,)


In [41]:
#B8 — Aggregating along an axis
print("B8 — mean per city:", np.nanmean(temps, axis=1), "| shape:", np.nanmean(temps, axis=1).shape)
print("B8 — max per city:", np.nanmax(temps, axis=1))
print("B8 — min per city:", np.nanmin(temps, axis=1))
print("B8 — std per city:", np.nanstd(temps, axis=1))

B8 — mean per city: [23.64285714 23.57142857 22.84615385 20.07142857 26.53846154] | shape: (5,)
B8 — max per city: [33. 35. 33. 35. 35.]
B8 — min per city: [17. 14. 14. 14. 15.]
B8 — std per city: [4.89324816 6.41108733 5.89453663 6.41943796 7.11028924]


In [42]:
print("B8 — mean per day:", np.nanmean(temps, axis=0), "| shape:", np.nanmean(temps, axis=0).shape)
print("B8 — max per day:", np.nanmax(temps, axis=0))

B8 — mean per day: [25.4  20.   19.   23.6  22.   22.75 27.6  26.   27.6  23.4  16.6  20.25
 25.8  25.4 ] | shape: (14,)
B8 — max per day: [33. 26. 28. 33. 31. 33. 35. 33. 35. 35. 21. 30. 33. 30.]


In [43]:
hottest_day_idx = np.nanargmax(temps, axis=1)
print("B8 — each city's hottest day:", days[hottest_day_idx])

B8 — each city's hottest day: ['D04' 'D09' 'D08' 'D07' 'D10']


In [44]:
#B9 — Reproducible randomness and a train/test split
flat_samples = temps.flatten()
n = flat_samples.size
 
np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)
split_point = int(n * 0.8)
train_idx, test_idx = idx[:split_point], idx[split_point:]
print("B9 — train shape:", train_idx.shape, "| test shape:", test_idx.shape)
print("B9 — sizes sum to 70:", train_idx.size + test_idx.size == 70)
print("B9 — no shared indices:", np.intersect1d(train_idx, test_idx).size == 0)

B9 — train shape: (56,) | test shape: (14,)
B9 — sizes sum to 70: True
B9 — no shared indices: True


In [45]:
np.random.seed(42)
idx2 = np.arange(n)
np.random.shuffle(idx2)
train_idx2, test_idx2 = idx2[:split_point], idx2[split_point:]
assert np.array_equal(train_idx, train_idx2) and np.array_equal(test_idx, test_idx2)
print("B9 — repeated split with same seed is identical: True")

B9 — repeated split with same seed is identical: True


In [46]:
#B10 — np.where , argmax , argmin
labels_grid = np.where(temps > 30, "hot", np.where(temps >= 22, "mild", "cold"))
print("B10a — label grid shape:", labels_grid.shape)

B10a — label grid shape: (5, 14)


In [47]:
scores = np.array([0.08, 0.62, 0.21, 0.09])
weather_labels = ["rain", "clear", "cloudy", "fog"]
predicted = weather_labels[np.argmax(scores)]
print("B10b — predicted label:", predicted)

B10b — predicted label: clear
